FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
COPY tsconfig.json ./
COPY apps/notification ./apps/notification
COPY libs ./libs
RUN npm ci
CMD ["npm", "run", "test:notification"]