FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
COPY tsconfig.json ./
COPY apps/subscription ./apps/subscription
COPY libs ./libs
RUN npm ci
CMD ["npm", "run", "test:subscription"]